# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8d2b182a6db1f1291f51cf41ccccf5fe9af5f25f0fcfab295624b00dbd7a403741b6facd30c8e922d73d073270eabac2727eac33c0bcfab216b2da63452e1db

test:
  secret_key_base: 17d5e65180cf3a5507354a3bf2cb5cd5e5f4190e313982ffa07c4f20ce4b1ccfd4dc146a2c70fb3f5fc33aaa25fec2284ea7435e311f536201736378e0cca760

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
